DEF_ERR(CAN_NOT_PARSE_NODE, 0)

DEF_ERR(INVALID_TYPE, 1)

DEF_ERR(INVALID_VALUE, 2)

DEF_ERR(INVALID_L_SON_PTR, 3)

DEF_ERR(INVALID_R_SON_PTR, 4)

DEF_ERR(INCORRECT_DESTINATION_PORT, 5)

DEF_ERR(VAR_STARTS_WITH_NUMBER, 6)

DEF_ERR(CAN_T_OPEN_LOGS, 7)